### PR TITLE
add method to tweet Gabby at 8AM and 10PM

### PR DESCRIPTION
**Pull request by nucle0tides**
I just.............need more love

### CODE REVIEW

**Comment by nucle0tides** [comment]
why did you merge my pull request before reviewing it?

**Comment by ejmg** [comment]
*👏because👏trust👏is👏critical👏and👏you👏broke👏that👏trust👏*

**Comment by nucle0tides** [comment]
tell that to your future employers pt 2

**Comment by ejmg** [comment]
this is why i have trust issues i'm closing this thread k

**Comment by ejmg** [comment]
now who has the final word huh

**Pull request merged**
